export const QUOTES_RO = [
  { text: "Fericirea vieții tale depinde de calitatea gândurilor tale.", author: "Marc Aurelius", mood: "calm" },
  { text: "Ai putere asupra minții tale, nu asupra evenimentelor exterioare. Realizează asta și vei găsi puterea.", author: "Marc Aurelius", mood: "strength" },
  { text: "Foarte puțin este necesar pentru o viață fericită — totul se află în interiorul tău, în modul tău de a gândi.", author: "Marc Aurelius", mood: "joy" },
  { text: "Nu mai pierde timp discutând despre cum ar trebui să fie un om bun. Fii unul.", author: "Marc Aurelius", mood: "action" },
  { text: "Dacă nu e corect — nu o face. Dacă nu e adevărat — nu o spune.", author: "Marc Aurelius", mood: "truth" },
  { text: "Când te trezești dimineața, gândește-te ce privilegiu prețios este să fii în viață — să respiri, să gândești, să te bucuri, să iubești.", author: "Marc Aurelius", mood: "joy" },
  { text: "Contemplă frumusețea vieții. Privește stelele și imaginează-te alergând cu ele.", author: "Marc Aurelius", mood: "cosmos" },
  { text: "Momentul prezent va exista mereu.", author: "Marc Aurelius", mood: "peace" },
  { text: "A fi curajos înseamnă a fi liber.", author: "Seneca", mood: "courage" },
  { text: "Norocul este ceea ce se întâmplă când pregătirea întâlnește oportunitatea.", author: "Seneca", mood: "action" },
  { text: "Suferim mai mult în imaginație decât în realitate.", author: "Seneca", mood: "peace" },
  { text: "În timp ce amânăm, viața trece.", author: "Seneca", mood: "action" },
  { text: "Folosește cât mai bine ce ai în puterea ta și acceptă restul așa cum vine.", author: "Epictet", mood: "calm" },
  { text: "Nu căuta binele în lucruri exterioare; caută-l în tine însuți.", author: "Epictet", mood: "inner" },
  { text: "Mai întâi spune-ți ce vrei să fii; apoi fă ce trebuie.", author: "Epictet", mood: "action" },
  { text: "Nu este liber cel ce nu este stăpân pe sine.", author: "Epictet", mood: "strength" },
  { text: "Nu ceea ce ți se întâmplă contează, ci cum reacționezi.", author: "Epictet", mood: "peace" },
  { text: "Mintea este totul. Ce gândești, devii.", author: "Buddha", mood: "inner" },
  { text: "Pacea vine din interior. Nu o căuta în exterior.", author: "Buddha", mood: "peace" },
  { text: "Nu locui în trecut, nu visa la viitor — concentrează-ți mintea pe momentul prezent.", author: "Buddha", mood: "calm" },
  { text: "Trei lucruri nu pot fi ascunse mult timp: soarele, luna și adevărul.", author: "Buddha", mood: "truth" },
  { text: "Nimeni nu ne salvează în afară de noi înșine.", author: "Buddha", mood: "strength" },
  { text: "Nu există drum spre fericire — fericirea este drumul.", author: "Buddha", mood: "joy" },
  { text: "Să știi ce știi și ce nu știi — aceasta este adevărata cunoaștere.", author: "Confucius", mood: "inner" },
  { text: "Viața este cu adevărat simplă, dar noi insistăm să o complicăm.", author: "Confucius", mood: "calm" },
  { text: "Alege o muncă pe care o iubești și nu va trebui să muncești nicio zi din viață.", author: "Confucius", mood: "purpose" },
  { text: "Nu contează cât de încet mergi, atâta timp cât nu te oprești.", author: "Confucius", mood: "strength" },
  { text: "Mergi acolo unde te duce inima.", author: "Confucius", mood: "action" },
  { text: "Respectă-te pe tine și ceilalți te vor respecta.", author: "Confucius", mood: "inner" },
  { text: "Frumusețea este pretutindeni. Nu toți o văd.", author: "Confucius", mood: "joy" },
  { text: "Aud și uit. Văd și îmi amintesc. Fac și înțeleg.", author: "Confucius", mood: "action" },
  { text: "Tăcerea este o sursă de mare putere.", author: "Lao Tzu", mood: "inner" },
  { text: "Natura nu se grăbește, și totuși totul se împlinește.", author: "Lao Tzu", mood: "calm" },
  { text: "Când las în urmă ceea ce sunt, devin ceea ce aș putea fi.", author: "Lao Tzu", mood: "growth" },
  { text: "O călătorie de o mie de leghe începe cu un singur pas.", author: "Lao Tzu", mood: "action" },
  { text: "Viața este o serie de schimbări naturale. Nu te opune lor.", author: "Lao Tzu", mood: "calm" },
  { text: "A stăpâni pe alții înseamnă forță. A te stăpâni pe tine înseamnă adevărata putere.", author: "Lao Tzu", mood: "strength" },
  { text: "Cunoașterea de sine este începutul întregii înțelepciuni.", author: "Aristotel", mood: "inner" },
  { text: "Suntem ceea ce facem în mod repetat. Excelența nu este un act, ci un obicei.", author: "Aristotel", mood: "action" },
  { text: "Fericirea depinde de noi înșine.", author: "Aristotel", mood: "joy" },
  { text: "O viață neexaminată nu merită trăită.", author: "Socrate", mood: "inner" },
  { text: "Știu că nu știu nimic.", author: "Socrate", mood: "inner" },
  { text: "Mirarea este începutul înțelepciunii.", author: "Socrate", mood: "growth" },
  { text: "Imaginația este mai importantă decât cunoașterea. Cunoașterea este limitată, imaginația cuprinde lumea.", author: "Albert Einstein", mood: "creativity" },
  { text: "O persoană care n-a greșit niciodată n-a încercat niciodată ceva nou.", author: "Albert Einstein", mood: "growth" },
  { text: "Viața e ca mersul pe bicicletă. Ca să-ți păstrezi echilibrul, trebuie să continui să pedalezi.", author: "Albert Einstein", mood: "vitality" },
  { text: "Încearcă să nu devii un om de succes, ci un om de valoare.", author: "Albert Einstein", mood: "purpose" },
  { text: "În mijlocul fiecărei dificultăți se ascunde o oportunitate.", author: "Albert Einstein", mood: "growth" },
  { text: "Creativitatea este inteligența care se distrează.", author: "Albert Einstein", mood: "creativity" },
  { text: "Cel care are un de ce poate suporta aproape orice cum.", author: "Friedrich Nietzsche", mood: "purpose" },
  { text: "Ceea ce nu mă ucide mă face mai puternic.", author: "Friedrich Nietzsche", mood: "strength" },
  { text: "Fără muzică, viața ar fi o greșeală.", author: "Friedrich Nietzsche", mood: "joy" },
  { text: "Dacă vrei să fii fericit — fii.", author: "Lev Tolstoi", mood: "joy" },
  { text: "Frumusețea va salva lumea.", author: "Fiodor Dostoievski", mood: "creativity" },
  { text: "Iubește viața mai mult decât sensul ei.", author: "Fiodor Dostoievski", mood: "joy" },
  { text: "Concizia este sora talentului.", author: "Anton Cehov", mood: "inner" },
  { text: "Cu toții suntem făcuți din materie stelară.", author: "Carl Sagan", mood: "cosmos" },
  { text: "Undeva, ceva incredibil așteaptă să fie descoperit.", author: "Carl Sagan", mood: "cosmos" },
  { text: "Pentru creaturi mici ca noi, doar iubirea face imensitatea universului suportabilă.", author: "Carl Sagan", mood: "love" },
  { text: "Fii schimbarea pe care vrei să o vezi în lume.", author: "Mahatma Gandhi", mood: "action" },
  { text: "Cei slabi nu pot ierta niciodată. Iertarea este atributul celor puternici.", author: "Mahatma Gandhi", mood: "strength" },
  { text: "Viitorul depinde de ceea ce faci astăzi.", author: "Mahatma Gandhi", mood: "action" },
  { text: "Credința înseamnă să faci primul pas chiar și când nu vezi toată scara.", author: "Martin Luther King Jr.", mood: "courage" },
  { text: "Întunericul nu poate alunga întunericul — doar lumina poate face asta.", author: "Martin Luther King Jr.", mood: "truth" },
  { text: "Momentul potrivit pentru a face ce e corect este întotdeauna acum.", author: "Martin Luther King Jr.", mood: "action" },
  { text: "Totul pare imposibil până când este realizat.", author: "Nelson Mandela", mood: "strength" },
  { text: "Nu pierd niciodată. Fie câștig, fie învăț.", author: "Nelson Mandela", mood: "growth" },
  { text: "Singura modalitate de a face o treabă grozavă este să iubești ceea ce faci.", author: "Steve Jobs", mood: "purpose" },
  { text: "Timpul tău e limitat, nu-l irosi trăind viața altcuiva.", author: "Steve Jobs", mood: "action" },
  { text: "Rămâi flămând. Rămâi nebun.", author: "Steve Jobs", mood: "growth" },
  { text: "Simplitatea este cea mai înaltă formă de sofisticare.", author: "Steve Jobs", mood: "inner" },
  { text: "Succesul nu e final, eșecul nu e fatal: curajul de a continua este ceea ce contează.", author: "Winston Churchill", mood: "strength" },
  { text: "Pesimistul vede dificultatea în fiecare oportunitate. Optimistul vede oportunitatea în fiecare dificultate.", author: "Winston Churchill", mood: "joy" },
  { text: "Fă ce poți, cu ce ai, acolo unde ești.", author: "Theodore Roosevelt", mood: "action" },
  { text: "Crede că poți și ești deja la jumătatea drumului.", author: "Theodore Roosevelt", mood: "strength" },
  { text: "Meritul aparține celui care se află cu adevărat în arenă.", author: "Theodore Roosevelt", mood: "courage" },
  { text: "Peste douăzeci de ani vei regreta mai mult lucrurile pe care nu le-ai făcut decât pe cele pe care le-ai făcut.", author: "Mark Twain", mood: "action" },
  { text: "Curajul este rezistența la frică, stăpânirea fricii — nu absența ei.", author: "Mark Twain", mood: "courage" },
  { text: "Oamenii vor uita ce ai spus, dar nu vor uita niciodată cum i-ai făcut să se simtă.", author: "Maya Angelou", mood: "love" },
  { text: "Creativitatea nu se epuizează. Cu cât o folosești mai mult, cu atât ai mai multă.", author: "Maya Angelou", mood: "creativity" },
  { text: "Între stimul și răspuns există un spațiu. În acel spațiu se află libertatea noastră.", author: "Viktor Frankl", mood: "inner" },
  { text: "Când nu mai putem schimba situația, suntem provocați să ne schimbăm pe noi înșine.", author: "Viktor Frankl", mood: "growth" },
  { text: "Sensul vieții este să-ți găsești darul. Scopul vieții este să-l dăruiești lumii.", author: "Pablo Picasso", mood: "purpose" },
  { text: "Inspirația există, dar trebuie să te găsească muncind.", author: "Pablo Picasso", mood: "action" },
  { text: "Dacă judeci oamenii, nu ai timp să-i iubești.", author: "Maica Tereza", mood: "love" },
  { text: "Pacea începe cu un zâmbet.", author: "Maica Tereza", mood: "peace" },
  { text: "Răspândește iubirea oriunde mergi. Nimeni să nu plece de la tine fără a fi mai fericit.", author: "Maica Tereza", mood: "love" },
  { text: "Nu toți cei care rătăcesc sunt pierduți.", author: "J.R.R. Tolkien", mood: "journey" },
  { text: "Chiar și cea mai mică persoană poate schimba cursul viitorului.", author: "J.R.R. Tolkien", mood: "purpose" },
  { text: "Tot ce trebuie să decidem este ce să facem cu timpul care ne este dat.", author: "J.R.R. Tolkien", mood: "action" },
  { text: "Fii tu însuți; toți ceilalți sunt deja ocupați.", author: "Oscar Wilde", mood: "inner" },
  { text: "A trăi este cel mai rar lucru din lume. Majoritatea oamenilor doar există.", author: "Oscar Wilde", mood: "action" },
  { text: "Cazi de șapte ori, ridică-te de opt.", author: "Proverb japonez", mood: "strength" },
  { text: "Drumul se face mergând.", author: "Înțelepciune populară", mood: "action" },
  { text: "Cel mai bun moment să plantezi un copac a fost acum douăzeci de ani. Al doilea cel mai bun moment este acum.", author: "Proverb chinezesc", mood: "action" },
  { text: "Durerea este temporară. Gloria este veșnică.", author: "Înțelepciune populară", mood: "strength" },
  { text: "Aleargă când poți. Mergi dacă trebuie. Târăște-te dacă e nevoie. Dar nu renunța niciodată.", author: "Dean Karnazes", mood: "strength" },
  { text: "Corpul tău poate suporta aproape orice. Mintea ta e cea pe care trebuie s-o convingi.", author: "Înțelepciune populară", mood: "strength" },
  { text: "O zi oarecare sau prima zi. Tu decizi.", author: "Înțelepciune populară", mood: "action" },
  { text: 'Fă-o acum. Uneori \u201emai târziu\u201d devine \u201eniciodată\u201d.', author: "Înțelepciune populară", mood: "action" },
  { text: "Dacă crezi că poți — ai dreptate. Dacă crezi că nu poți — tot ai dreptate.", author: "Henry Ford", mood: "strength" },
  { text: "Eșecul este pur și simplu oportunitatea de a o lua de la capăt, de data aceasta mai inteligent.", author: "Henry Ford", mood: "growth" },
  { text: "Visează ca și cum ai trăi veșnic. Trăiește ca și cum ai muri azi.", author: "James Dean", mood: "joy" },
  { text: "Viața este ceea ce ți se întâmplă în timp ce ești ocupat cu alte planuri.", author: "John Lennon", mood: "joy" },
  { text: "Nu căuta vinovați — caută soluții.", author: "Henry Ford", mood: "action" },
  { text: "Înțelepciunea este să știi când să taci.", author: "Înțelepciune populară", mood: "inner" },
  { text: "În adâncul iernii, am descoperit în cele din urmă că în mine trăiește o vară de neînvins.", author: "Albert Camus", mood: "strength" },
  { text: "O navă în port este în siguranță, dar navele nu sunt construite pentru asta.", author: "Înțelepciune populară", mood: "courage" },
  { text: "Nu merge pe unde duce drumul; mergi pe unde nu e drum și lasă o urmă.", author: "Ralph Waldo Emerson", mood: "courage" },
  { text: "A fi tu însuți într-o lume care încearcă constant să te facă altceva este cea mai mare realizare.", author: "Ralph Waldo Emerson", mood: "inner" },
  { text: "Mintea, odată lărgită de o idee nouă, nu se mai întoarce niciodată la dimensiunile anterioare.", author: "Ralph Waldo Emerson", mood: "growth" },
];
