export const QUOTES_EN = [
  { text: "The happiness of your life depends on the quality of your thoughts.", author: "Marcus Aurelius", mood: "calm" },
  { text: "You have power over your mind, not outside events. Realize this, and you will find strength.", author: "Marcus Aurelius", mood: "strength" },
  { text: "Very little is needed to make a happy life — it is all within yourself, in your way of thinking.", author: "Marcus Aurelius", mood: "joy" },
  { text: "Waste no more time arguing about what a good man should be. Be one.", author: "Marcus Aurelius", mood: "action" },
  { text: "If it is not right, do not do it. If it is not true, do not say it.", author: "Marcus Aurelius", mood: "truth" },
  { text: "When you arise in the morning, think of what a precious privilege it is to be alive — to breathe, to think, to enjoy, to love.", author: "Marcus Aurelius", mood: "joy" },
  { text: "Dwell on the beauty of life. Watch the stars, and see yourself running with them.", author: "Marcus Aurelius", mood: "cosmos" },
  { text: "The present moment will always have existed.", author: "Marcus Aurelius", mood: "peace" },
  { text: "To be brave is to be free.", author: "Seneca", mood: "courage" },
  { text: "Luck is what happens when preparation meets opportunity.", author: "Seneca", mood: "action" },
  { text: "We suffer more often in imagination than in reality.", author: "Seneca", mood: "peace" },
  { text: "While we postpone, life speeds by.", author: "Seneca", mood: "action" },
  { text: "Make the best use of what is in your power, and take the rest as it happens.", author: "Epictetus", mood: "calm" },
  { text: "Seek not the good in external things; seek it in yourselves.", author: "Epictetus", mood: "inner" },
  { text: "First say to yourself what you would be; and then do what you have to do.", author: "Epictetus", mood: "action" },
  { text: "No man is free who is not master of himself.", author: "Epictetus", mood: "strength" },
  { text: "It's not what happens to you, but how you react to it that matters.", author: "Epictetus", mood: "peace" },
  { text: "The mind is everything. What you think, you become.", author: "Buddha", mood: "inner" },
  { text: "Peace comes from within. Do not seek it without.", author: "Buddha", mood: "peace" },
  { text: "Do not dwell in the past, do not dream of the future, concentrate the mind on the present moment.", author: "Buddha", mood: "calm" },
  { text: "Three things cannot be long hidden: the sun, the moon, and the truth.", author: "Buddha", mood: "truth" },
  { text: "No one saves us but ourselves.", author: "Buddha", mood: "strength" },
  { text: "There is no path to happiness — happiness is the path.", author: "Buddha", mood: "joy" },
  { text: "To know what you know and what you do not know — that is true knowledge.", author: "Confucius", mood: "inner" },
  { text: "Life is really simple, but we insist on making it complicated.", author: "Confucius", mood: "calm" },
  { text: "Choose a job you love, and you will never have to work a day in your life.", author: "Confucius", mood: "purpose" },
  { text: "It does not matter how slowly you go, as long as you do not stop.", author: "Confucius", mood: "strength" },
  { text: "Go where your heart leads you.", author: "Confucius", mood: "action" },
  { text: "Respect yourself and others will respect you.", author: "Confucius", mood: "inner" },
  { text: "Everything has beauty, but not everyone sees it.", author: "Confucius", mood: "joy" },
  { text: "I hear and I forget. I see and I remember. I do and I understand.", author: "Confucius", mood: "action" },
  { text: "Silence is a source of great strength.", author: "Lao Tzu", mood: "inner" },
  { text: "Nature does not hurry, yet everything is accomplished.", author: "Lao Tzu", mood: "calm" },
  { text: "When I let go of what I am, I become what I might be.", author: "Lao Tzu", mood: "growth" },
  { text: "A journey of a thousand miles begins with a single step.", author: "Lao Tzu", mood: "action" },
  { text: "Life is a series of natural and spontaneous changes. Don't resist them.", author: "Lao Tzu", mood: "calm" },
  { text: "Mastering others is strength. Mastering yourself is true power.", author: "Lao Tzu", mood: "strength" },
  { text: "Knowing yourself is the beginning of all wisdom.", author: "Aristotle", mood: "inner" },
  { text: "We are what we repeatedly do. Excellence, then, is not an act, but a habit.", author: "Aristotle", mood: "action" },
  { text: "Happiness depends upon ourselves.", author: "Aristotle", mood: "joy" },
  { text: "The unexamined life is not worth living.", author: "Socrates", mood: "inner" },
  { text: "I know that I know nothing.", author: "Socrates", mood: "inner" },
  { text: "Wonder is the beginning of wisdom.", author: "Socrates", mood: "growth" },
  { text: "Imagination is more important than knowledge. Knowledge is limited. Imagination encircles the world.", author: "Albert Einstein", mood: "creativity" },
  { text: "A person who never made a mistake never tried anything new.", author: "Albert Einstein", mood: "growth" },
  { text: "Life is like riding a bicycle. To keep your balance, you must keep moving.", author: "Albert Einstein", mood: "vitality" },
  { text: "Try not to become a man of success, but rather a man of value.", author: "Albert Einstein", mood: "purpose" },
  { text: "In the middle of difficulty lies opportunity.", author: "Albert Einstein", mood: "growth" },
  { text: "Creativity is intelligence having fun.", author: "Albert Einstein", mood: "creativity" },
  { text: "He who has a why to live can bear almost any how.", author: "Friedrich Nietzsche", mood: "purpose" },
  { text: "What does not kill me makes me stronger.", author: "Friedrich Nietzsche", mood: "strength" },
  { text: "Without music, life would be a mistake.", author: "Friedrich Nietzsche", mood: "joy" },
  { text: "If you want to be happy, be.", author: "Leo Tolstoy", mood: "joy" },
  { text: "Beauty will save the world.", author: "Fyodor Dostoevsky", mood: "creativity" },
  { text: "Love life more than the meaning of it.", author: "Fyodor Dostoevsky", mood: "joy" },
  { text: "Brevity is the sister of talent.", author: "Anton Chekhov", mood: "inner" },
  { text: "We are all made of star-stuff.", author: "Carl Sagan", mood: "cosmos" },
  { text: "Somewhere, something incredible is waiting to be known.", author: "Carl Sagan", mood: "cosmos" },
  { text: "For small creatures such as we, the vastness is bearable only through love.", author: "Carl Sagan", mood: "love" },
  { text: "Be the change you wish to see in the world.", author: "Mahatma Gandhi", mood: "action" },
  { text: "The weak can never forgive. Forgiveness is the attribute of the strong.", author: "Mahatma Gandhi", mood: "strength" },
  { text: "The future depends on what you do today.", author: "Mahatma Gandhi", mood: "action" },
  { text: "Faith is taking the first step even when you don't see the whole staircase.", author: "Martin Luther King Jr.", mood: "courage" },
  { text: "Darkness cannot drive out darkness — only light can do that.", author: "Martin Luther King Jr.", mood: "truth" },
  { text: "The time is always right to do what is right.", author: "Martin Luther King Jr.", mood: "action" },
  { text: "It always seems impossible until it's done.", author: "Nelson Mandela", mood: "strength" },
  { text: "I never lose. I either win or learn.", author: "Nelson Mandela", mood: "growth" },
  { text: "The only way to do great work is to love what you do.", author: "Steve Jobs", mood: "purpose" },
  { text: "Your time is limited, don't waste it living someone else's life.", author: "Steve Jobs", mood: "action" },
  { text: "Stay hungry. Stay foolish.", author: "Steve Jobs", mood: "growth" },
  { text: "Simplicity is the ultimate sophistication.", author: "Steve Jobs", mood: "inner" },
  { text: "Success is not final, failure is not fatal: it is the courage to continue that counts.", author: "Winston Churchill", mood: "strength" },
  { text: "A pessimist sees the difficulty in every opportunity; an optimist sees the opportunity in every difficulty.", author: "Winston Churchill", mood: "joy" },
  { text: "Do what you can, with what you have, where you are.", author: "Theodore Roosevelt", mood: "action" },
  { text: "Believe you can and you're halfway there.", author: "Theodore Roosevelt", mood: "strength" },
  { text: "It is not the critic who counts. The credit belongs to the man who is actually in the arena.", author: "Theodore Roosevelt", mood: "courage" },
  { text: "Twenty years from now you will be more disappointed by the things you didn't do than by the ones you did.", author: "Mark Twain", mood: "action" },
  { text: "Courage is resistance to fear, mastery of fear — not absence of fear.", author: "Mark Twain", mood: "courage" },
  { text: "People will forget what you said, but they will never forget how you made them feel.", author: "Maya Angelou", mood: "love" },
  { text: "Creativity doesn't run out. The more you use, the more you have.", author: "Maya Angelou", mood: "creativity" },
  { text: "Between stimulus and response there is a space. In that space is our freedom.", author: "Viktor Frankl", mood: "inner" },
  { text: "When we are no longer able to change a situation, we are challenged to change ourselves.", author: "Viktor Frankl", mood: "growth" },
  { text: "The meaning of life is to find your gift. The purpose of life is to give it away.", author: "Pablo Picasso", mood: "purpose" },
  { text: "Inspiration exists, but it has to find you working.", author: "Pablo Picasso", mood: "action" },
  { text: "If you judge people, you have no time to love them.", author: "Mother Teresa", mood: "love" },
  { text: "Peace begins with a smile.", author: "Mother Teresa", mood: "peace" },
  { text: "Spread love everywhere you go. Let no one ever come to you without leaving happier.", author: "Mother Teresa", mood: "love" },
  { text: "Not all those who wander are lost.", author: "J.R.R. Tolkien", mood: "journey" },
  { text: "Even the smallest person can change the course of the future.", author: "J.R.R. Tolkien", mood: "purpose" },
  { text: "All we have to decide is what to do with the time that is given us.", author: "J.R.R. Tolkien", mood: "action" },
  { text: "Be yourself; everyone else is already taken.", author: "Oscar Wilde", mood: "inner" },
  { text: "To live is the rarest thing in the world. Most people exist, that is all.", author: "Oscar Wilde", mood: "action" },
  { text: "Fall seven times, stand up eight.", author: "Japanese Proverb", mood: "strength" },
  { text: "The road is mastered by walking.", author: "Folk Wisdom", mood: "action" },
  { text: "The best time to plant a tree was twenty years ago. The second best time is now.", author: "Chinese Proverb", mood: "action" },
  { text: "Pain is temporary. Glory is forever.", author: "Folk Wisdom", mood: "strength" },
  { text: "Run when you can. Walk if you have to. Crawl if you must. Just never give up.", author: "Dean Karnazes", mood: "strength" },
  { text: "Your body can stand almost anything. It's your mind that you have to convince.", author: "Folk Wisdom", mood: "strength" },
  { text: "One day or day one. You decide.", author: "Folk Wisdom", mood: "action" },
  { text: "Do it now. Sometimes 'later' becomes 'never'.", author: "Folk Wisdom", mood: "action" },
  { text: "Whether you think you can, or you think you can't — you're right.", author: "Henry Ford", mood: "strength" },
  { text: "Failure is simply the opportunity to begin again, this time more intelligently.", author: "Henry Ford", mood: "growth" },
  { text: "Dream as if you'll live forever. Live as if you'll die today.", author: "James Dean", mood: "joy" },
  { text: "Life is what happens to you while you're busy making other plans.", author: "John Lennon", mood: "joy" },
  { text: "Don't find fault, find a remedy.", author: "Henry Ford", mood: "action" },
  { text: "Wisdom is knowing when to be silent.", author: "Folk Wisdom", mood: "inner" },
  { text: "In the depth of winter, I finally learned that within me there lay an invincible summer.", author: "Albert Camus", mood: "strength" },
  { text: "A ship in harbor is safe, but that's not what ships are built for.", author: "Folk Wisdom", mood: "courage" },
  { text: "Do not go where the path may lead; go instead where there is no path and leave a trail.", author: "Ralph Waldo Emerson", mood: "courage" },
  { text: "To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment.", author: "Ralph Waldo Emerson", mood: "inner" },
  { text: "The mind, once stretched by a new idea, never returns to its original dimensions.", author: "Ralph Waldo Emerson", mood: "growth" },
];
